CREATE PROCEDURE dbo.CreateTables AS

DROP TABLE IF EXISTS Flight
DROP TABLE IF EXISTS Aircraft
DROP TABLE IF EXISTS Airline
DROP TABLE IF EXISTS Airport
DROP TABLE IF EXISTS Country

CREATE TABLE Country (
	CountryID INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(200) NOT NULL,
	URL NVARCHAR(200) NOT NULL
)

CREATE TABLE Airport (
	AirportID NVARCHAR(3) PRIMARY KEY,
	CountryID INT FOREIGN KEY REFERENCES Country(CountryID) NOT NULL,
	Name NVARCHAR(200) NOT NULL,
	Location GEOGRAPHY ,
	URL NVARCHAR(200) NOT NULL
)

CREATE TABLE Airline (
	AirlineID INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(200) NOT NULL,
	URL NVARCHAR(200) NOT NULL
)

CREATE TABLE Aircraft (
	AircraftID INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(200) NULL
)

CREATE TABLE Flight (
	FlightID INT PRIMARY KEY IDENTITY(1,1),
	Flight NVARCHAR(200) NOT NULL,
	Codeshare BIT NOT NULL,
	SourceID NVARCHAR(3) FOREIGN KEY REFERENCES Airport(AirportID) NOT NULL,
	DestinationID NVARCHAR(3) FOREIGN KEY REFERENCES Airport(AirportID) NOT NULL,
	AirlineID INT FOREIGN KEY REFERENCES Airline(AirlineID) NULL,
	AircraftID INT FOREIGN KEY REFERENCES Airline(AirlineID) NULL,
	Date DATE NOT NULL,
	DepartureScheduled DATETIME NULL,
	DepartureActual DATETIME NULL,
	ArrivalScheduled DATETIME NULL,
	ArrivalActual DATETIME NULL,
	Status NVARCHAR(200) NOT NULL,
	URL NVARCHAR(200) NOT NULL
)